<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="DotNetEnv" Version="3.2.0" />
        <PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.3.9" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.2" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="8.0.2" />
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.2" />
        <PackageReference Include="Quartz" Version="3.17.1" />
        <PackageReference Include="Quartz.Extensions.Hosting" Version="3.17.1" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Configurations\Seed\" />
    </ItemGroup>

</Project>
