<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\mini_1_helpdesk_ticket.Application\mini_1_helpdesk_ticket.Application.csproj" />
        <ProjectReference Include="..\mini_1_helpdesk_ticket.Infrastructure\mini_1_helpdesk_ticket.Infrastructure.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Folder Include="Document\plan-phase-1\" />
        <Folder Include="Document\plan-phase-2\" />
    </ItemGroup>

</Project>
