// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using mini_1_helpdesk_ticket.Repo;

#nullable disable

namespace mini_1_helpdesk_ticket.Repo.Migrations
{
    [DbContext(typeof(HelpdeskDbContext))]
    [Migration("20260802061420_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("ticket_code_seq");

            modelBuilder.Entity("mini_1_helpdesk_ticket.Repo.Entity.Label", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("color");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_labels");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_labels_slug");

                    b.ToTable("labels", null, t =>
                        {
                            t.HasCheckConstraint("ck_labels_color_hex", "color ~ '^#[0-9A-Fa-f]{6}$'");

                            t.HasCheckConstraint("ck_labels_name_not_blank", "length(btrim(name)) > 0");

                            t.HasCheckConstraint("ck_labels_slug_format", "slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'");
                        });
                });

            modelBuilder.Entity("mini_1_helpdesk_ticket.Repo.Entity.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AssigneeName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("assignee_name");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Medium")
                        .HasColumnName("priority");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Open")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_tickets");

                    b.HasIndex("AssigneeName")
                        .HasDatabaseName("ix_tickets_assignee_name");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_tickets_code");

                    b.HasIndex("CreatedAt", "Id")
                        .IsDescending()
                        .HasDatabaseName("ix_tickets_created_at_id");

                    b.HasIndex("Status", "Priority")
                        .HasDatabaseName("ix_tickets_status_priority");

                    b.ToTable("tickets", null, t =>
                        {
                            t.HasCheckConstraint("ck_tickets_description_not_blank", "length(btrim(description)) > 0");

                            t.HasCheckConstraint("ck_tickets_priority_valid", "priority IN ('Low','Medium','High', 'Urgent')");

                            t.HasCheckConstraint("ck_tickets_status_valid", "status IN ('Open','Closed','Resolved','InProgress')");

                            t.HasCheckConstraint("ck_tickets_title_not_blank", "length(btrim(title)) > 0");
                        });
                });

            modelBuilder.Entity("mini_1_helpdesk_ticket.Repo.Entity.TicketComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("author_name");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_ticket_comments");

                    b.HasIndex("TicketId", "CreatedAt", "Id")
                        .HasDatabaseName("ix_ticket_comments_ticket_id_created_at");

                    b.ToTable("ticket_comments", null, t =>
                        {
                            t.HasCheckConstraint("ck_ticket_comments_author_not_blank", "length(btrim(author_name)) > 0");

                            t.HasCheckConstraint("ck_ticket_comments_content_not_blank", "length(btrim(content)) > 0");
                        });
                });

            modelBuilder.Entity("mini_1_helpdesk_ticket.Repo.Entity.TicketLabel", b =>
                {
                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_id");

                    b.Property<Guid>("LabelId")
                        .HasColumnType("uuid")
                        .HasColumnName("label_id");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.HasKey("TicketId", "LabelId")
                        .HasName("pk_ticket_labels");

                    b.HasIndex("LabelId")
                        .HasDatabaseName("ix_ticket_labels_label_id");

                    b.ToTable("ticket_labels", (string)null);
                });

            modelBuilder.Entity("mini_1_helpdesk_ticket.Repo.Entity.TicketComment", b =>
                {
                    b.HasOne("mini_1_helpdesk_ticket.Repo.Entity.Ticket", "Ticket")
                        .WithMany("TicketComments")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_comments_tickets_ticket_id");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("mini_1_helpdesk_ticket.Repo.Entity.TicketLabel", b =>
                {
                    b.HasOne("mini_1_helpdesk_ticket.Repo.Entity.Label", "Label")
                        .WithMany("TicketLabels")
                        .HasForeignKey("LabelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_labels_labels_label_id");

                    b.HasOne("mini_1_helpdesk_ticket.Repo.Entity.Ticket", "Ticket")
                        .WithMany("TicketLabels")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_labels_tickets_ticket_id");

                    b.Navigation("Label");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("mini_1_helpdesk_ticket.Repo.Entity.Label", b =>
                {
                    b.Navigation("TicketLabels");
                });

            modelBuilder.Entity("mini_1_helpdesk_ticket.Repo.Entity.Ticket", b =>
                {
                    b.Navigation("TicketComments");

                    b.Navigation("TicketLabels");
                });
#pragma warning restore 612, 618
        }
    }
}
